### ISSUE TITLE
Is this supposed to work with Centos 6 ?

### ISSUE THREAD

**Issue by guiniol** [dracut-crypt-ssh/dracut-crypt-ssh#7] opened 2017-03-13 14:49 UTC
Hello,

I installed this on a Cento 7 machine and it works like a charm. However, I couldn't get it to work on a Centos 6 machine. I added `add_dracutmodules+="crypt-ssh"` to `/etc/dracut.conf` and regenerated the initramfs, however, when I extract it, there is not a single mention of `crypt-ssh` or `dropbear`. At boot, the network starts (options `ip=dhcp netroot=dummy`) but the machine does not accept connections.
There is no `modules.d/99base/rdsosreport.sh` file either so I don't know how to debug anything.
Any advice?

**Comment by guiniol** [comment] 2017-03-13 16:29
So.
I figured that the `module-setup.sh` script must be separated into `install` and `check` which source `module-setup.sh` and call their namesake function. Then, the ecdsa key must be dropped because the version of `dropbearconvert` cannot handle the openssh ecdsa keys.
And now, dropbear does start, but I cannot connect to it. I get `Pubkey auth attempt with unknown algo` (after adding `-E` to dropbear). If I launch dropbear after boot and try to connect to it using the same public key, it works, so I don't know what could be going on.

**Comment by mazzystr** [comment] 2017-03-13 19:38
It doesn't work for me under CentOS 7.2

Module doesn't even appear to be starting up.

Got any tips?

**Comment by guiniol** [comment] 2017-03-13 20:12
I installed it, followed the instructions and it worked. For Centos7, there shouldn't be anything to change.
Are you sure that:
1. You modified the grub config and regenerated the grub file? If so, can you at least ping the machine? This is independant of the module. The options added to grub start the network interface and configure it, so it should answer to ping.
2. Did you configure dropbear with your ssh key and (optionally) the server key?

**Comment by rbu** [comment] 2017-03-22 10:45
@mazzystr, it is expected to work with CentOS 7, although I am only testing it on an up-to-date system. Do you see the initramfs connecting to the network (in the DHCP server log/client list)? If so, does the system respond to ping? Does dropbear start?

@guiniol, I have not attempted to port to CentOS 6, but I am happy to accept your changes as a pull request that adds CentOS 6 support.
Regarding your key problem, it looks like the old Dropbear does not like your public key format. What format are you using?

**Comment by guiniol** [comment] 2017-03-22 14:27
@rbu that was my thought too. However, once booted, if I launch dropbear then I can connect to it. I also tried generating the keys with the dropbear but got the same error.

**Comment by rbu** [comment] 2017-03-22 16:26
@guiniol, it is possible that libnss is not installed into the initramfs properly. ``modules/60crypt-ssh/module-setup.sh`` currently does "``dracut_install pkill setterm /lib64/libnss_files.so.2``".

Does that library path exist for you (are you on x84_64)?

This issue sounds similar to https://bugs.launchpad.net/ubuntu/+source/dropbear/+bug/834174

**Comment by mazzystr** [comment] 2017-03-22 16:30
I couldn't get this code to work.

I ended up rolling my own based on some other folks's work
https://github.com/mazzystr/Configurations/tree/master/40earlyssh

I'm not fond of building modules outside of whats included with RHEL nor having static network configuration when my hosts have reserved dynamic ips.

**Comment by guiniol** [comment] 2017-03-22 16:46
@rbu thanks for the link to the bug. However, I think my case is different, here's is the output of find in the extracted initrd:
```
$ find ./ -name '*libnss*'
./lib64/libnss_dns-2.12.so
./lib64/libnss_nisplus.so.2
./lib64/libnss_files-2.12.so
./lib64/libnss_dns.so.2
./lib64/libnss_files.so.2
./lib64/libnss_nisplus-2.12.so
./usr/lib64/libnss3.so
./usr/lib64/libnss_nisplus.so
./usr/lib64/libnss_dns.so
./usr/lib64/libnss_files.so
./usr/lib64/libnssutil3.so
```

**Comment by guiniol** [comment] 2017-03-22 16:47
hummm
unless dropbear is looking into the `/lib/` directory. Will have to try.

**Comment by guiniol** [comment] 2017-03-23 09:56
It still refuses my public key...

**Comment by rbu** [comment] 2017-03-23 12:35
@guiniol thanks for trying. I'd like to experiment on this myself, can you share the exact changes you made to support building on CentOS 6? It's fine if your changes are not mergeable (i.e., they work on both 6 and 7), but I'm of course happy if they are.

@mazzystr
1. Thanks for publicly documenting your build steps.
2. You can do either static or dynamic network configurations easily using the RHEL base tool dracut, see [README](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/blob/master/README.md#32-enable-network-access-during-boot).
3. I provide builds using Fedora infrastructure (COPR), so you should be able to validate the sources.
4. I can emphasize with using tools outside the base or epel repos, [but our attempts to push this to upstream dracut failed](https://github.com/dracutdevs/dracut/pull/43#issuecomment-171901956). The alternative is maintaining this package in EPEL, which I would like to do if we have enough users who confirmed this works in a variety of settings. If you feel inclined to debug what broke in your case, feel free to share it (in a new issue though, not to hijack this one).

**Comment by guiniol** [comment] 2017-03-23 14:55
Here is the patch I made:

[patch.txt](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/files/865114/patch.txt)

The modification to `dropbear-start.sh` is only to enable debug output.
I had to disable the `ecdsa` key type, but that may be a problem with how it's configured. I also left the `/lib/libnss_files.so.2` install, but I don't think it's necessary.

I also had to add `ip=dhcp netroot=dummy` to the kernel command line to get the network to be on.

I think the patch makes it not work for Centos 7 for now.

**Comment by guiniol** [comment] 2017-03-23 14:57
If there's anything I can test, don't hesitate.

**Comment by guiniol** [comment] 2017-03-23 17:04
I created  VM to test this, and I do get the same behaviour.
I found bug report indicating that the `Pubkey auth attempt with unknown algo` could simply be dropbear not finding the authorized_keys file, but it does seem to check in the right places.

**Comment by guiniol** [comment] 2017-03-23 17:17
Using `dbclient` instead of `ssh` I get a bit further and get a `Login attempt for nonexistent user` error instead.

**Comment by guiniol** [comment] 2017-03-23 17:20
Scratch that. `dbclient` doesn't read the ssh config and was indeed using the wrong user. The error I get now is `exit before auth`. In the client, I get `No auth methods could be used`

**Comment by guiniol** [comment] 2017-04-13 15:11
@rbu did you manage to get somewhere?
I haven't had much time, but I never got further than my previous message...

**Comment by mazzystr** [comment] 2017-04-13 15:23
Sorry.  I haven't had a chance to revisit this but I'm still following along because of it's potential :)

**Comment by rbu** [comment] 2018-04-26 19:09
I'm happy to accept a Pull Request adding CentOS 6 support, since it still has over 2 years of support from the vendor. However, I am not working on this myself. I'll leave this bug open for people to subscribe to... maybe for another year.

**Comment by ahesford** [comment] 2021-05-17 17:41
Closing, CentOS 6 was EOL November 2020.

**Closed as completed by ahesford** 2021-05-17 17:41 UTC
Labels: help wanted
