### ISSUE TITLE
Kernel panic Fedora 

### ISSUE THREAD

**Issue by Lilleengen** [dracut-crypt-ssh/dracut-crypt-ssh#2] opened 2016-03-03 16:51 UTC
After selecting a boot-option in grub2 i am presented with a kernal panic.
I added dracutmodules+="crypt-ssh" to dracut.conf and ran dracut -f.
Running Fedora on 4.0.5-300.fc22.x86_64.
What the kernal panic says (cant see all of it):

```
[1.445921] Hardware name: MSI MS-7793/FM2-A85XA-G65 (MS-7793), BIOS V1.4 11/28/2012

[1.445949] 0000000000000000 0000000035f40581 ffff88012a3afd78 ffffffff817834f4

[1.446082] 0000000000000000 ffffffff81a3a1a0 ffff88012a3afdf8 ffffffff817834f4

[1.446206] 3132383000000010 ffff88012a3afe08 ffff88012a3afda8 0000000035f48581

[1.446330] Call Trace:

[1.446360]     [<ffffffff817834f4>] dump_stack+0x45/0x57 

[1.446388]     [<ffffffff81782264>] panic+0xd0/0x203

[1.446417]     [<ffffffff81d395cc>] mount_block_root+0x209/0x2a6

[1.446445]     [<ffffffff81d396bd>] mount_root+0x54/0x58 

[1.446472]     [<ffffffff81d397fe>] prepare_namespace+0x13d/0x22f

[1.446500]     [<ffffffff81d3926c>] kernel_init_freeable+0x20b/0x22f

[1.446529]     [<ffffffff81779d40>] ? rest_init+0x80/0x80

[1.446556]     [<ffffffff81779d4e>] kernel_init+0xe/0xf0

[1.446584]     [<ffffffff81789a58>] ret_from_fork+0x58/0x90

[1.446612]     [<ffffffff81779d40>] ? rest_init+0x80/0x80

[1.446698] Kernel Offset: 0x0 from 0xffffffff81000000 (relocation range: 0xfffffffff80000000-0xffffffff9fffffff)

[1.446774] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```

**Comment by rbu** [comment] 2016-03-04 17:36
This is surprising. The dropbear component should be optional and not disturb the regular boot. Were there any warnings when you built the initrd? Could you please retry with the fedora 22 RPM from https://copr.fedorainfracloud.org/coprs/rbu/dracut-crypt-ssh/

Either:

```
dnf copr enable rbu/dracut-crypt-ssh
dnf install dracut-crypt-ssh
```

Or download the RPM from https://copr.fedorainfracloud.org/coprs/rbu/dracut-crypt-ssh/build/165653/ manually

**Comment by Lilleengen** [comment] 2016-03-04 18:09
Nope, no warning. The error does only show if dracutmodules+="crypt-ssh" is present in dracut.conf. Will try to install the binary within 24 hours and report back.

**Comment by rbu** [comment] 2016-03-06 11:21
You can now refer to the updated installation steps in the README

**Comment by rbu** [comment] 2016-12-13 21:15
I'm closing this since you haven't responded and I am not able to reproduce. Feel free to reopen if you experience this again.

**Closed as completed by rbu** 2016-12-13 21:15 UTC
